version: 2
jobs:
  build:
    machine:
      node:
        version: 6.11.0
      environment:
        PATH: "${PATH}:${HOME}/.yarn/bin"
        YARN_VERSION: 1.1.0
    dependencies:
      pre:
        - |
          if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
          fi
      override:
        -  yarn install --pure-lockfile --no-progress
    cache_directories:
        - ~/.yarn
        - ~/.yarn-cache
        - ~/.cache/yarn
    test:
      override:
        - yarn test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}